#!/usr/bin/env python

from Tkinter  import *
root = Tk()
colour = StringVar()
colour.set('blue')
def colourUpdate():
    l.config(fg='red')
    root.update()

btn = Button(root, text = "Click Me", command = colourUpdate)
l = Label(root, textvariable=colour, fg = colour.get())
l.pack()
btn.pack()
root.mainloop()
