#!/usr/bin/python

# Gui for the code

from Tkinter import *
top = Tk()

var = StringVar()
label = Label(top, textvariable=var, relief=RAISED , anchor=CENTER)

var.set("1")
label.pack()
top.mainloop()
